version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 5
      semver-major-days: 31
      semver-minor-days: 8
      semver-patch-days: 4
    groups:
      # All patch updates together, may be merged when CI is green.
      patch-updates:
        update-types: ["patch"]

      # All minor updates together. Requires green CI + manual check.
      minor-updates:
        update-types: ["minor"]

    # Space left: 3 PRs of ungrouped major updates. Requires green CI + manual check.
    open-pull-requests-limit: 5

  # These update less often, so we leave them ungrouped.
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
