minimum_prek_version = "0.3.11"

[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "check-toml"

[[repos.hooks]]
id = "end-of-file-fixer"

[[repos.hooks]]
id = "trailing-whitespace"

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.11"

[[repos.hooks]]
id = "ruff-check"
types_or = ["python", "pyi"]
args = ["--fix"]

[[repos.hooks]]
id = "ruff-format"
types_or = ["python", "pyi"]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "mypy"
name = "mypy"
entry = "uv run mypy ."
language = "system"
types = ["python"]
pass_filenames = false
